<?php
/**
 * Magento 2 extensions for Payright Payment
 *
 * @author Payright
 * @copyright 2016-2018 Payright https://www.payright.com.au
 */

// ini_set("display_errors", "0");

if ($block->IsProductPageInstallmentTextActive() == "1") {

    $getInstallmentData = $block->getInstallmentsAmount();

    if ($getInstallmentData != 'exceed_amount' && $getInstallmentData != 'APIError') {
        ?>
        Or
        <strong><?php echo $getInstallmentData['numberOfRepayments']; ?></strong> <?php echo $getInstallmentData['repaymentFrequency'] ?> payments of $
        <strong><?php echo $getInstallmentData['loanAmountPerPayment']; ?></strong>  with <span
                class="payright-logo"><img></span>
        <a href="#" class="payright-modal-popup-trigger">Info</a>

        <?php
    }

}
?>


